### PR TITLE
Fix File Markdown File Extension Typo

### PR DESCRIPTION
**Pull request by Ma5onic**
File had `.mdx` extension instead of `.md`

### CODE REVIEW

**Comment by QuintenQVD0** [comment]
Mdx should be right? Does it not work?

**Comment by Ma5onic** [comment]
@QuintenQVD0 Thanks for the quick reply. All other documentation files in the repo are in `.md`, and `.mdx` is not commonly used for standard markdown. While the file does render correctly—likely due to Linux's handling of files not being heavily dependent on extensions and the robust error handling of your documentation framework—it does create issues when editing locally. Markdown editors like Obsidian and VSCode expect `.md` extensions to properly recognize and handle markdown syntax. This could be confusing for contributors trying to work on the docs.

**Comment by QuintenQVD0** [comment]
The way docusaurus handles this is that it needs .mdx files.

Vscode has a create extention to show syntax for mdx format as it is a offical format that is needed in the futute of docusaurus as md will be droped in the future.

**Comment by Ma5onic** [comment]
Good to know, noted.
Thanks

**Pull request closed without merging**
